# SPDX-License-Identifier: LicenseRef-CSSL-1.0

check_threshold_variance(physim.5g.nr_dlsim.basic.test1 "DLSCH encoding time" AVG 31 ABS_VAR 7)
check_threshold_variance(physim.5g.nr_dlsim.basic.test2 "DLSCH encoding time" AVG 36 ABS_VAR 8)
check_threshold_variance(physim.5g.nr_dlsim.basic.test3 "DLSCH encoding time" AVG 49 ABS_VAR 10)
check_threshold_variance(physim.5g.nr_dlsim.basic.test4 "DLSCH encoding time" AVG 33 ABS_VAR 7)
check_threshold_variance(physim.5g.nr_dlsim.basic.test5 "DLSCH encoding time" AVG 33 ABS_VAR 7)
check_threshold_variance(physim.5g.nr_dlsim.basic.test6 "DLSCH encoding time" AVG 31 ABS_VAR 7)
check_threshold_variance(physim.5g.nr_dlsim.basic.test7 "DLSCH encoding time" AVG 5 ABS_VAR 3)
check_threshold_variance(physim.5g.nr_dlsim.basic.test8 "DLSCH encoding time" AVG 20 ABS_VAR 4)
check_threshold_variance(physim.5g.nr_dlsim.offset.test1 "DLSCH encoding time" AVG 32 ABS_VAR 7)
check_threshold_variance(physim.5g.nr_dlsim.offset.test2 "DLSCH encoding time" AVG 25 ABS_VAR 5)
check_threshold_variance(physim.5g.nr_dlsim.offset.test3 "DLSCH encoding time" AVG 30 ABS_VAR 6)
check_threshold_variance(physim.5g.nr_dlsim.offset.test4 "DLSCH encoding time" AVG 34 ABS_VAR 7)
check_threshold_variance(physim.5g.nr_dlsim.offset.test5 "DLSCH encoding time" AVG 30 ABS_VAR 6)
check_threshold_variance(physim.5g.nr_dlsim.mcs.mimo.test1 "DLSCH encoding time" AVG 72 ABS_VAR 15)
check_threshold_variance(physim.5g.nr_dlsim.mcs.mimo.test2 "DLSCH encoding time" AVG 36 ABS_VAR 8)
check_threshold_variance(physim.5g.nr_dlsim.mcs.mimo.test3 "DLSCH encoding time" AVG 83 ABS_VAR 17)
check_threshold_variance(physim.5g.nr_dlsim.mcs.mimo.test4 "DLSCH encoding time" AVG 79 ABS_VAR 16)
check_threshold_variance(physim.5g.nr_dlsim.mcs.mimo.test5 "DLSCH encoding time" AVG 20 ABS_VAR 6)
check_threshold_variance(physim.5g.nr_dlsim.mcs.mimo.test6 "DLSCH encoding time" AVG 39 ABS_VAR 8)
check_threshold_variance(physim.5g.nr_dlsim.mcs.mimo.test7 "DLSCH encoding time" AVG 48 ABS_VAR 10)
check_threshold_variance(physim.5g.nr_dlsim.mcs.mimo.test8 "DLSCH encoding time" AVG 141 ABS_VAR 29)
check_threshold_variance(physim.5g.nr_dlsim.mcs.mimo.test9 "DLSCH encoding time" AVG 32 ABS_VAR 7)
check_threshold_variance(physim.5g.nr_dlsim.dmrs.ptrs.test1 "DLSCH encoding time" AVG 31 ABS_VAR 7)
check_threshold_variance(physim.5g.nr_dlsim.dmrs.ptrs.test2 "DLSCH encoding time" AVG 31 ABS_VAR 7)
check_threshold_variance(physim.5g.nr_dlsim.dmrs.ptrs.test3 "DLSCH encoding time" AVG 31 ABS_VAR 7)
check_threshold_variance(physim.5g.nr_dlsim.dmrs.ptrs.test4 "DLSCH encoding time" AVG 31 ABS_VAR 7)
check_threshold_variance(physim.5g.nr_dlsim.dmrs.ptrs.test5 "DLSCH encoding time" AVG 31 ABS_VAR 7)
check_threshold_variance(physim.5g.nr_dlsim.dmrs.ptrs.test6 "DLSCH encoding time" AVG 31 ABS_VAR 7)

check_threshold_variance(physim.5g.nr_ulsim.misc.test1 "ULSCH total decoding time"    AVG 211  ABS_VAR 42)
check_threshold_variance(physim.5g.nr_ulsim.misc.test2 "ULSCH total decoding time"    AVG 361  ABS_VAR 72)
check_threshold_variance(physim.5g.nr_ulsim.misc.test3 "ULSCH total decoding time"    AVG 364  ABS_VAR 73)
check_threshold_variance(physim.5g.nr_ulsim.misc.test4 "ULSCH total decoding time"    AVG 320  ABS_VAR 64)
check_threshold_variance(physim.5g.nr_ulsim.misc.test5 "ULSCH total decoding time"    AVG 791  ABS_VAR 158)
check_threshold_variance(physim.5g.nr_ulsim.misc.test6 "ULSCH total decoding time"    AVG 940  ABS_VAR 188)
check_threshold_variance(physim.5g.nr_ulsim.misc.test7 "ULSCH total decoding time"    AVG 186  ABS_VAR 37)
check_threshold_variance(physim.5g.nr_ulsim.misc.test8 "ULSCH total decoding time"    AVG 95   ABS_VAR 19)
check_threshold_variance(physim.5g.nr_ulsim.misc.test9 "ULSCH total decoding time"    AVG 95   ABS_VAR 19)
check_threshold_variance(physim.5g.nr_ulsim.misc.test10 "ULSCH total decoding time"   AVG 112  ABS_VAR 22)
check_threshold_variance(physim.5g.nr_ulsim.misc.test11 "ULSCH total decoding time"   AVG 30   ABS_VAR 6)
check_threshold_variance(physim.5g.nr_ulsim.misc.test12 "ULSCH total decoding time"   AVG 65   ABS_VAR 13)
check_threshold_variance(physim.5g.nr_ulsim.misc.test13 "ULSCH total decoding time"   AVG 60   ABS_VAR 12)
check_threshold_variance(physim.5g.nr_ulsim.misc.test14 "ULSCH total decoding time"   AVG 760  ABS_VAR 152)
check_threshold_variance(physim.5g.nr_ulsim.misc.test15 "ULSCH total decoding time"   AVG 72   ABS_VAR 14)
check_threshold_variance(physim.5g.nr_ulsim.sc-fdma.test1 "ULSCH total decoding time" AVG 184  ABS_VAR 37)
check_threshold_variance(physim.5g.nr_ulsim.sc-fdma.test2 "ULSCH total decoding time" AVG 140  ABS_VAR 28)
check_threshold_variance(physim.5g.nr_ulsim.sc-fdma.test3 "ULSCH total decoding time" AVG 746  ABS_VAR 149)
check_threshold_variance(physim.5g.nr_ulsim.sc-fdma.test4 "ULSCH total decoding time" AVG 485  ABS_VAR 97)
check_threshold_variance(physim.5g.nr_ulsim.sc-fdma.test5 "ULSCH total decoding time" AVG 84   ABS_VAR 17)
check_threshold_variance(physim.5g.nr_ulsim.mimo.test1 "ULSCH total decoding time"    AVG 400  ABS_VAR 80)
check_threshold_variance(physim.5g.nr_ulsim.mimo.test2 "ULSCH total decoding time"    AVG 271  ABS_VAR 54)
check_threshold_variance(physim.5g.nr_ulsim.mimo.test3 "ULSCH total decoding time"    AVG 837  ABS_VAR 167)
check_threshold_variance(physim.5g.nr_ulsim.mimo.test4 "ULSCH total decoding time"    AVG 1203 ABS_VAR 241)
check_threshold_variance(physim.5g.nr_ulsim.mimo.test5 "ULSCH total decoding time"    AVG 891  ABS_VAR 178)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test1 "ULSCH total decoding time"    AVG 789  ABS_VAR 158)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test2 "ULSCH total decoding time"    AVG 794  ABS_VAR 159)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test3 "ULSCH total decoding time"    AVG 878  ABS_VAR 176)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test4 "ULSCH total decoding time"    AVG 232  ABS_VAR 46)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test5 "ULSCH total decoding time"    AVG 238  ABS_VAR 48)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test6 "ULSCH total decoding time"    AVG 254  ABS_VAR 51)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test7 "ULSCH total decoding time"    AVG 402  ABS_VAR 80)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test8 "ULSCH total decoding time"    AVG 425  ABS_VAR 85)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test9 "ULSCH total decoding time"    AVG 454  ABS_VAR 91)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test10 "ULSCH total decoding time"   AVG 778  ABS_VAR 156)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test11 "ULSCH total decoding time"   AVG 815  ABS_VAR 163)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test12 "ULSCH total decoding time"   AVG 902  ABS_VAR 180)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test13 "ULSCH total decoding time"   AVG 230  ABS_VAR 46)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test14 "ULSCH total decoding time"   AVG 241  ABS_VAR 48)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test15 "ULSCH total decoding time"   AVG 257  ABS_VAR 51)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test16 "ULSCH total decoding time"   AVG 408  ABS_VAR 82)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test17 "ULSCH total decoding time"   AVG 428  ABS_VAR 86)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test18 "ULSCH total decoding time"   AVG 468  ABS_VAR 94)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test19 "ULSCH total decoding time"   AVG 782  ABS_VAR 156)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test20 "ULSCH total decoding time"   AVG 806  ABS_VAR 161)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test21 "ULSCH total decoding time"   AVG 905  ABS_VAR 181)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test22 "ULSCH total decoding time"   AVG 1869 ABS_VAR 374)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test23 "ULSCH total decoding time"   AVG 1974 ABS_VAR 395)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test24 "ULSCH total decoding time"   AVG 2486 ABS_VAR 497)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test25 "ULSCH total decoding time"   AVG 316  ABS_VAR 63)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test26 "ULSCH total decoding time"   AVG 280  ABS_VAR 56)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test27 "ULSCH total decoding time"   AVG 1170 ABS_VAR 234)
check_threshold_variance(physim.5g.nr_ulsim.3gpp.test28 "ULSCH total decoding time"   AVG 1251 ABS_VAR 250)

check_threshold_variance(physim.5g.ldpctest.test1  "Encoding time mean:" AVG 6 ABS_VAR 2)
check_threshold_variance(physim.5g.ldpctest.test1  "Decoding time mean:" AVG 49 ABS_VAR 10)
check_threshold_variance(physim.5g.ldpctest.test2  "Encoding time mean:" AVG 9 ABS_VAR 2)
check_threshold_variance(physim.5g.ldpctest.test2  "Decoding time mean:" AVG 52 ABS_VAR 10)
check_threshold_variance(physim.5g.ldpctest.test3  "Encoding time mean:" AVG 8 ABS_VAR 2)
check_threshold_variance(physim.5g.ldpctest.test3  "Decoding time mean:" AVG 56 ABS_VAR 11)
check_threshold_variance(physim.5g.ldpctest.test4  "Encoding time mean:" AVG 11 ABS_VAR 3)
check_threshold_variance(physim.5g.ldpctest.test4  "Decoding time mean:" AVG 60 ABS_VAR 12)
check_threshold_variance(physim.5g.ldpctest.test5  "Encoding time mean:" AVG 10 ABS_VAR 2)
check_threshold_variance(physim.5g.ldpctest.test5  "Decoding time mean:" AVG 63 ABS_VAR 13)
check_threshold_variance(physim.5g.ldpctest.test6  "Encoding time mean:" AVG 16 ABS_VAR 4)
check_threshold_variance(physim.5g.ldpctest.test6  "Decoding time mean:" AVG 68 ABS_VAR 14)
check_threshold_variance(physim.5g.ldpctest.test7  "Encoding time mean:" AVG 14 ABS_VAR 3)
check_threshold_variance(physim.5g.ldpctest.test7  "Decoding time mean:" AVG 75 ABS_VAR 15)
check_threshold_variance(physim.5g.ldpctest.test8  "Encoding time mean:" AVG 17 ABS_VAR 4)
check_threshold_variance(physim.5g.ldpctest.test8  "Decoding time mean:" AVG 81 ABS_VAR 16)
check_threshold_variance(physim.5g.ldpctest.test9  "Encoding time mean:" AVG 19 ABS_VAR 4)
check_threshold_variance(physim.5g.ldpctest.test9  "Decoding time mean:" AVG 93 ABS_VAR 19)
check_threshold_variance(physim.5g.ldpctest.test10 "Encoding time mean:" AVG 14 ABS_VAR 3)
check_threshold_variance(physim.5g.ldpctest.test10 "Decoding time mean:" AVG 94 ABS_VAR 19)
check_threshold_variance(physim.5g.ldpctest.test11 "Encoding time mean:" AVG 2 ABS_VAR 1)
check_threshold_variance(physim.5g.ldpctest.test11 "Decoding time mean:" AVG 4 ABS_VAR 1)
check_threshold_variance(physim.5g.ldpctest.test12 "Encoding time mean:" AVG 10 ABS_VAR 2)
check_threshold_variance(physim.5g.ldpctest.test12 "Decoding time mean:" AVG 5 ABS_VAR 1)
check_threshold_variance(physim.5g.ldpctest.test13 "Encoding time mean:" AVG 18 ABS_VAR 4)
check_threshold_variance(physim.5g.ldpctest.test13 "Decoding time mean:" AVG 6 ABS_VAR 1)
check_threshold_variance(physim.5g.ldpctest.test14 "Encoding time mean:" AVG 44 ABS_VAR 9)
check_threshold_variance(physim.5g.ldpctest.test14 "Decoding time mean:" AVG 8 ABS_VAR 2)
check_threshold_variance(physim.5g.ldpctest.test15 "Encoding time mean:" AVG 49 ABS_VAR 10)
check_threshold_variance(physim.5g.ldpctest.test15 "Decoding time mean:" AVG 8 ABS_VAR 2)
check_threshold_variance(physim.5g.ldpctest.test16 "Encoding time mean:" AVG 3 ABS_VAR 1)
check_threshold_variance(physim.5g.ldpctest.test16 "Decoding time mean:" AVG 9 ABS_VAR 2)
check_threshold_variance(physim.5g.ldpctest.test17 "Encoding time mean:" AVG 3 ABS_VAR 1)
check_threshold_variance(physim.5g.ldpctest.test17 "Decoding time mean:" AVG 8 ABS_VAR 2)
check_threshold_variance(physim.5g.ldpctest.test18 "Encoding time mean:" AVG 4 ABS_VAR 1)
check_threshold_variance(physim.5g.ldpctest.test18 "Decoding time mean:" AVG 20 ABS_VAR 4)
check_threshold_variance(physim.5g.ldpctest.test19 "Encoding time mean:" AVG 8 ABS_VAR 2)
check_threshold_variance(physim.5g.ldpctest.test19 "Decoding time mean:" AVG 29 ABS_VAR 6)
check_threshold_variance(physim.5g.ldpctest.test20 "Encoding time mean:" AVG 10 ABS_VAR 2)
check_threshold_variance(physim.5g.ldpctest.test20 "Decoding time mean:" AVG 35 ABS_VAR 7)

check_threshold_variance(physim.5g.nr_ulsim_mu_mimo.test1 "ULSCH total decoding time" AVG 334 ABS_VAR 67)
check_threshold_variance(physim.5g.nr_ulsim_mu_mimo.test2 "ULSCH total decoding time" AVG 290 ABS_VAR 58)
check_threshold_variance(physim.5g.nr_ulsim_mu_mimo.test3 "ULSCH total decoding time" AVG 2107 ABS_VAR 421)
check_threshold_variance(physim.5g.nr_ulsim_mu_mimo.test4 "ULSCH total decoding time" AVG 2743 ABS_VAR 549)
check_threshold_variance(physim.5g.nr_ulsim_mu_mimo.test5 "ULSCH total decoding time" AVG 2148 ABS_VAR 430)
