uicc0 = {
  imsi = "001010123456780";
  key = "00112233445566778899aabbccddeeff";
  opc= "63bfa50ee6523365ff14c1f45f88737d";
  pdu_sessions = ({
  dnn = "internet";
  nssai_sst = 1;
});
};
device = { name = "oai_zmqdevif"; };
zmq = (
  {
    tx_channels = ("tcp://0.0.0.0:4557");
    rx_channels = ("tcp://10.53.1.3:4556");
    channel_effects_enabled = 1;

    rx_tap_file = "/traces/ue2_dl_real.txt";
    rx_tap_file_imag = "/traces/ue2_dl_imag.txt";
    rx_tap_count = 10;
    rx_path_gain_db = 0.0;

    tx_tap_file      = "/traces/ue2_ul_real.txt";
    tx_tap_file_imag = "/traces/ue2_ul_imag.txt";
    tx_tap_count     = 10;
  }
);
uecap_file = "/uecap.xml";
