/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

/*!
 * \brief rrc types and subtypes
 */

#ifndef RRC_TYPES_H_
#define RRC_TYPES_H_

typedef enum Rrc_State_e {
  RRC_STATE_INACTIVE=0,
  RRC_STATE_IDLE,
  RRC_STATE_CONNECTED,

  RRC_STATE_FIRST = RRC_STATE_INACTIVE,
  RRC_STATE_LAST = RRC_STATE_CONNECTED,
} Rrc_State_t;

typedef enum Rrc_Sub_State_e {
  RRC_SUB_STATE_INACTIVE = 0,

  RRC_SUB_STATE_IDLE_SEARCHING,
  RRC_SUB_STATE_IDLE_RECEIVING_SIB,
  RRC_SUB_STATE_IDLE_SIB_COMPLETE,
  RRC_SUB_STATE_IDLE_CONNECTING,
  RRC_SUB_STATE_IDLE,

  RRC_SUB_STATE_CONNECTED,
} Rrc_Sub_State_t;

typedef enum Rrc_Msg_Type_e {
  UE_CAPABILITY_DUMMY = 0xa0,
  UE_CAPABILITY_ENQUIRY,
  NRUE_CAPABILITY_ENQUIRY,
  UE_CAPABILITY_INFO,
  NRUE_CAPABILITY_INFO,
  RRC_MEASUREMENT_PROCEDURE,
  NR_UE_RRC_MEASUREMENT,
  RRC_CONFIG_COMPLETE_REQ,
  NR_RRC_CONFIG_COMPLETE_REQ,
  OAI_TUN_IFACE_NSA
} Rrc_Msg_Type_t;


#endif /* RRC_TYPES_H_ */
