/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

/*!
 * \brief rrc types and subtypes
 */

#ifndef RRC_TYPES_NB_IOT_H_
#define RRC_TYPES_NB_IOT_H_

typedef enum Rrc_State_NB_IoT_e {
  RRC_STATE_INACTIVE_NB_IoT=0,
  RRC_STATE_IDLE_NB_IoT,
  RRC_STATE_CONNECTED_NB_IoT,

  RRC_STATE_FIRST_NB_IoT = RRC_STATE_INACTIVE_NB_IoT,
  RRC_STATE_LAST_NB_IoT = RRC_STATE_CONNECTED_NB_IoT,
} Rrc_State_NB_IoT_t;

typedef enum Rrc_Sub_State_NB_IoT_e {
  RRC_SUB_STATE_INACTIVE_NB_IoT=0,

  RRC_SUB_STATE_IDLE_SEARCHING_NB_IoT,
  RRC_SUB_STATE_IDLE_RECEIVING_SIB_NB_IoT,
  RRC_SUB_STATE_IDLE_SIB_COMPLETE_NB_IoT,
  RRC_SUB_STATE_IDLE_CONNECTING_NB_IoT,
  RRC_SUB_STATE_IDLE_NB_IoT,

  RRC_SUB_STATE_CONNECTED_NB_IoT,

  RRC_SUB_STATE_INACTIVE_FIRST_NB_IoT = RRC_SUB_STATE_INACTIVE_NB_IoT,
  RRC_SUB_STATE_INACTIVE_LAST_NB_IoT = RRC_SUB_STATE_INACTIVE_NB_IoT,

  RRC_SUB_STATE_IDLE_FIRST_NB_IoT = RRC_SUB_STATE_IDLE_SEARCHING_NB_IoT,
  RRC_SUB_STATE_IDLE_LAST_NB_IoT = RRC_SUB_STATE_IDLE_NB_IoT,

  RRC_SUB_STATE_CONNECTED_FIRST_NB_IoT = RRC_SUB_STATE_CONNECTED_NB_IoT,
  RRC_SUB_STATE_CONNECTED_LAST_NB_IoT = RRC_SUB_STATE_CONNECTED_NB_IoT,
} Rrc_Sub_State_NB_IoT_t;

#endif /* RRC_TYPES_H_ */
