/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

/* Header file generated by fdesign on Tue Nov 13 09:42:50 2012 */

#ifndef FD_nr_scope_h_
#define FD_nr_scope_h_
#include <simple_executable.h>
#include <common/utils/system.h>
#include <common/openairinterface5g_limits.h>
#include "common/ran_context.h"
#include <openair1/PHY/defs_gNB.h>
#include "PHY/defs_gNB.h"
//#include "PHY/defs_nrUE.h"
//#include "PHY/impl_defs_top.h"
#include "PHY/defs_nr_UE.h"

#include <openair1/PHY/TOOLS/phy_scope_interface.h>

extern RAN_CONTEXT_t RC;
#endif
