# SPDX-License-Identifier: MIT

kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "oai-gnb-fhi72"
  namespace: "oaicicd-ran"
spec:
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 0.5
        memory: 1Gi
    nodeSelector:
        node-role.kubernetes.io/fhi72: ""
    runPolicy: "Serial"
    source:
        type: "Binary"
        secrets:
          - secret:
              name: etc-pki-entitlement
            destinationDir: etc-pki-entitlement
    strategy:
        dockerStrategy:
            dockerfilePath: "docker/Dockerfile.gNB.fhi72.rhel9"
    output:
        to:
            kind: "ImageStreamTag"
            name: "oai-gnb-fhi72:latest"
