# SPDX-License-Identifier: MIT

### Resource consumption 16Gi, 10CPU
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "ran-base"
  namespace: "oaicicd-ran"
spec:
    runPolicy: "Serial"
    nodeSelector:
        node-role.kubernetes.io/ran-base: ""
    source:
        type: "Binary"
        secrets:
          - secret:
              name: etc-pki-entitlement
            destinationDir: etc-pki-entitlement
    strategy:
        dockerStrategy:
            dockerfilePath: "docker/Dockerfile.base.rhel9"
    output:
        to:
            kind: "ImageStreamTag"
            name: "ran-base:latest"
