{
 "title": "RRC",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gnb_id",
    "label": "gNB ID",
    "query": {
     "query": "SELECT gnb_id FROM cell GROUP BY gnb_id"
    }
   },
   {
    "name": "gnb_du_id",
    "label": "gNB DU ID",
    "query": {
     "query": "SELECT gnb_du_id from rrcs GROUP BY gnb_du_id"
    }
   }
  ]
 },
 "panels": [
  { "title": "RRC connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mean",
   "type": "stat",
   "description": "Mean number of RRC connections",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"rrc_connection_number_max_nof_rrc_connections\" AS 'max', \"rrc_connection_number_mean_nof_rrc_connections\" AS 'mean' FROM \"rrcs\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"gnb_id\" = '$gnb_id' AND \"gnb_du_id\" == '$gnb_du_id'"
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "description": "Maximum number of RRC connections",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  {
   "title": "Mean inactive",
   "type": "stat",
   "description": "Mean number of inactive RRC connections",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"rrc_connection_number_max_nof_inactive_rrc_connections\" AS 'max_inactive', \"rrc_connection_number_mean_nof_inactive_rrc_connections\" AS 'mean_inactive' FROM \"rrcs\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"gnb_id\" = '$gnb_id' AND \"gnb_du_id\" == '$gnb_du_id'"
    }
   ]
  },
  {
   "title": "Max inactive",
   "type": "stat",
   "description": "Maximum number of inactive RRC connections",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "panelId": 19 }
   ]
  },
  { "title": "RRC connection establishment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Attempted",
   "type": "stat",
   "description": "Attempted RRC connection establishments",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_emergency\" AS 'emergency',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_high_prio_access\" AS 'high_prio_access',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_mcs_prio_access\" AS 'mcs_prio_access',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_mo_data\" AS 'mo_data',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_mo_sig\" AS 'mo_sig',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_mo_sms\" AS 'mo_sms',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_mo_video_call\" AS 'mo_video_call',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_mo_voice_call\" AS 'mo_voice_call',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_mps_prio_access\" AS 'mps_prio_access',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_mt_access\" AS 'mt_access',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_unknown\" AS 'unknown'\n              \nFROM \"rrcs\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"gnb_id\" = '$gnb_id' AND gnb_du_id ='$gnb_du_id'"
    }
   ]
  },
  {
   "title": "Successful",
   "type": "stat",
   "description": "Successful RRC connection establishments",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_emergency\" AS 'emergency',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_high_prio_access\" AS 'high_prio_access',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_mcs_prio_access\" AS 'mcs_prio_access',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_mo_data\" AS 'mo_data',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_mo_sig\" AS 'mo_sig',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_mo_sms\" AS 'mo_sms',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_mo_video_call\" AS 'mo_video_call',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_mo_voice_call\" AS 'mo_voice_call',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_mps_prio_access\" AS 'mps_prio_access',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_mt_access\" AS 'mt_access',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_unknown\" AS 'unknown'\n\nFROM \"rrcs\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"gnb_id\" = '$gnb_id' AND \"gnb_du_id\" == '$gnb_du_id'\n"
    }
   ]
  },
  {
   "title": "RRC connection establishment (details)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attempted (detail)",
     "type": "bargauge",
     "description": "Attempted RRC connection establishments (detail)",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 6 }
     ]
    },
    {
     "title": "Successful (details)",
     "type": "bargauge",
     "description": "Successful RRC connection establishments (details)",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 7 }
     ]
    }
   ]
  },
  { "title": "RRC connection reestablishment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Attempted",
   "type": "stat",
   "description": "Attempted RRC connection reestablishments",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    \"rrc_connection_reestablishment_attempted_rrc_connection_reestablishments\",\n    \"rrc_connection_reestablishment_successful_rrc_connection_reestablishments_with_ue_context\",\n    \"rrc_connection_reestablishment_successful_rrc_connection_reestablishments_without_ue_context\"\nFROM \"rrcs\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"gnb_id\" = '$gnb_id' AND \"gnb_du_id\" == '$gnb_du_id'"
    }
   ]
  },
  {
   "title": "Successful with ue context",
   "type": "stat",
   "description": "Successful RRC connection reestablishments with ue context",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 12 }
   ]
  },
  {
   "title": "Successful without ue context",
   "type": "stat",
   "description": "Successful RRC connection reestablishments without ue context",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 12 }
   ]
  },
  { "title": "RRC connection resume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Attempted resume",
   "type": "stat",
   "description": "Attempted RRC connection resumes",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \n    \"rrc_connection_resume_attempted_rrc_connection_resumes_emergency\" AS 'emergency',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_high_prio_access\" AS 'high_prio_access',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_mcs_prio_access\" AS 'mcs_prio_access',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_mo_data\" AS 'mo_data',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_mo_sig\" AS 'mo_sig',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_mo_sms\" AS 'mo_sms',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_mo_video_call\" AS 'mo_video_call',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_mo_voice_call\" AS 'mo_voice_call',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_mps_prio_access\" AS 'mps_prio_access',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_mt_access\" AS 'mt_access',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_unknown\" AS 'unknown'\n              \nFROM \"rrcs\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"gnb_id\" = '$gnb_id' AND gnb_du_id ='$gnb_du_id'"
    }
   ]
  },
  {
   "title": "Successful resume",
   "type": "stat",
   "description": "Successful RRC connection resumes",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    \"rrc_connection_resume_successful_rrc_connection_resumes_emergency\" AS 'emergency',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_high_prio_access\" AS 'high_prio_access',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_mcs_prio_access\" AS 'mcs_prio_access',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_mo_data\" AS 'mo_data',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_mo_sig\" AS 'mo_sig',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_mo_sms\" AS 'mo_sms',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_mo_video_call\" AS 'mo_video_call',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_mo_voice_call\" AS 'mo_voice_call',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_mps_prio_access\" AS 'mps_prio_access',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_mt_access\" AS 'mt_access',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_unknown\" AS 'unknown'\n\nFROM \"rrcs\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"gnb_id\" = '$gnb_id' AND \"gnb_du_id\" == '$gnb_du_id'\n"
    }
   ]
  },
  {
   "title": "Attempted resumes followed by RRC setup",
   "type": "stat",
   "description": "Attempted RRC connection resumes followed by RRC setup",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \n    \"rrc_connection_resume_attempted_rrc_connection_resumes_followed_by_rrc_setup_emergency\" AS 'emergency',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_followed_by_rrc_setup_high_prio_access\" AS 'high_prio_access',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_followed_by_rrc_setup_mcs_prio_access\" AS 'mcs_prio_access',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_followed_by_rrc_setup_mo_data\" AS 'mo_data',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_followed_by_rrc_setup_mo_sig\" AS 'mo_sig',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_followed_by_rrc_setup_mo_sms\" AS 'mo_sms',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_followed_by_rrc_setup_mo_video_call\" AS 'mo_video_call',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_followed_by_rrc_setup_mo_voice_call\" AS 'mo_voice_call',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_followed_by_rrc_setup_mps_prio_access\" AS 'mps_prio_access',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_followed_by_rrc_setup_mt_access\" AS 'mt_access',\n    \"rrc_connection_resume_attempted_rrc_connection_resumes_followed_by_rrc_setup_unknown\" AS 'unknown'\n              \nFROM \"rrcs\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"gnb_id\" = '$gnb_id' AND gnb_du_id ='$gnb_du_id'"
    }
   ]
  },
  {
   "title": "Connection resumes followed by network release",
   "type": "stat",
   "description": "RRC connection resumes followed by network release",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \n    \"rrc_connection_resume_rrc_connection_resumes_followed_by_network_release_emergency\" AS 'emergency',\n    \"rrc_connection_resume_rrc_connection_resumes_followed_by_network_release_high_prio_access\" AS 'high_prio_access',\n    \"rrc_connection_resume_rrc_connection_resumes_followed_by_network_release_mcs_prio_access\" AS 'mcs_prio_access',\n    \"rrc_connection_resume_rrc_connection_resumes_followed_by_network_release_mo_data\" AS 'mo_data',\n    \"rrc_connection_resume_rrc_connection_resumes_followed_by_network_release_mo_sig\" AS 'mo_sig',\n    \"rrc_connection_resume_rrc_connection_resumes_followed_by_network_release_mo_sms\" AS 'mo_sms',\n    \"rrc_connection_resume_rrc_connection_resumes_followed_by_network_release_mo_video_call\" AS 'mo_video_call',\n    \"rrc_connection_resume_rrc_connection_resumes_followed_by_network_release_mo_voice_call\" AS 'mo_voice_call',\n    \"rrc_connection_resume_rrc_connection_resumes_followed_by_network_release_mps_prio_access\" AS 'mps_prio_access',\n    \"rrc_connection_resume_rrc_connection_resumes_followed_by_network_release_mt_access\" AS 'mt_access',\n    \"rrc_connection_resume_rrc_connection_resumes_followed_by_network_release_unknown\" AS 'unknown'\n              \nFROM \"rrcs\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"gnb_id\" = '$gnb_id' AND gnb_du_id ='$gnb_du_id'"
    }
   ]
  },
  {
   "title": "Successful resume with fallback",
   "type": "stat",
   "description": "Successful RRC connection resumes with fallback",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \n    \"rrc_connection_resume_successful_rrc_connection_resumes_with_fallback_emergency\" AS 'emergency',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_with_fallback_high_prio_access\" AS 'high_prio_access',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_with_fallback_mcs_prio_access\" AS 'mcs_prio_access',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_with_fallback_mo_data\" AS 'mo_data',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_with_fallback_mo_sig\" AS 'mo_sig',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_with_fallback_mo_sms\" AS 'mo_sms',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_with_fallback_mo_video_call\" AS 'mo_video_call',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_with_fallback_mo_voice_call\" AS 'mo_voice_call',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_with_fallback_mps_prio_access\" AS 'mps_prio_access',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_with_fallback_mt_access\" AS 'mt_access',\n    \"rrc_connection_resume_successful_rrc_connection_resumes_with_fallback_unknown\" AS 'unknown'\n              \nFROM \"rrcs\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"gnb_id\" = '$gnb_id' AND gnb_du_id ='$gnb_du_id'"
    }
   ]
  },
  {
   "title": "RRC connection resume (details)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attempted resume (detail)",
     "type": "bargauge",
     "description": "Attempted RRC connection resumes (detail)",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 66 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 22 }
     ]
    },
    {
     "title": "Successful resume (details)",
     "type": "bargauge",
     "description": "Successful RRC connection resumes (details)",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 66 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 23 }
     ]
    },
    {
     "title": "Attempted resumes followed by RRC setup (details)",
     "type": "bargauge",
     "description": "Attempted RRC connection resumes followed by RRC setup (details)",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 74 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 26 }
     ]
    },
    {
     "title": "Connection resumes followed by network release (details)",
     "type": "bargauge",
     "description": "RRC connection resumes followed by network release (details)",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 74 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 27 }
     ]
    },
    {
     "title": "Successful resumes with fallback (details)",
     "type": "bargauge",
     "description": "Successful RRC connection resumes with fallback (details)",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 82 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 28 }
     ]
    }
   ]
  },
  { "title": "Handover (all DUs)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Requested",
   "type": "stat",
   "description": "Number of handover executions requested",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"nof_handover_executions_requested\", \"nof_successful_handover_executions\" FROM \"cu_cp\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"gnb_id\" = '$gnb_id' "
    }
   ]
  },
  {
   "title": "Successful",
   "type": "stat",
   "description": "Number of successful handover executions",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 16 }
   ]
  }
 ]
}