# Copyright (c) Microsoft Corporation. Licensed under the MIT license.
#
# EdgeRIC-on-Janus DL scheduling codelet (telemetry + control on mac_sched_dl_ctrl).

PROTO_AND_SCHEMA := \
	dl_sched_report^dl_sched_report \
	dl_mcs_report^dl_mcs_report

include ../Makefile.defs
include ../Makefile.common
