# SPDX-License-Identifier: LicenseRef-CSSL-1.0

#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface BUILD service
#   Valid for Ubuntu 24.04 to cross-compile for ARM64
#
#---------------------------------------------------------------------

FROM ran-base:latest AS ran-build

RUN rm -Rf /oai-ran
WORKDIR /oai-ran
COPY . .

# build all targets so final targets can be created afterwards
RUN /bin/sh oaienv && \
    cd cmake_targets && \
    mkdir -p log ran_build/build ran_build/build-cross && \
    cd ran_build/build && \
    cmake ../../.. -GNinja && \
    ninja generate_T && \
    cd ../build-cross/ && \
    # install missing libyaml-cpp-dev for arm64
    apt install -y libyaml-cpp-dev:arm64 && \
    cmake ../../.. -GNinja -DENABLE_TELNETSRV=ON \
      -DCMAKE_TOOLCHAIN_FILE=../../../cmake_targets/cross-arm.cmake -DNATIVE_DIR=../build \
      -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror" && \
    ninja -k10 dlsim ulsim ldpctest polartest smallblocktest nr_pbchsim nr_dlschsim nr_ulschsim nr_dlsim nr_ulsim nr_pucchsim nr_prachsim lte-softmodem nr-softmodem nr-cuup oairu lte-uesoftmodem nr-uesoftmodem params_libconfig coding rfsimulator telnetsrv
