# SPDX-License-Identifier: LicenseRef-CSSL-1.0

#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface BUILD service
#   Valid for Rocky 9
#
#---------------------------------------------------------------------

ARG BASE_IMAGE=docker.io/rockylinux:9
FROM ran-base:latest AS gnb-base

FROM ran-build:latest AS gnb-build

COPY ./libori.so /usr/local/lib

# build AW2S fronthaul lib
WORKDIR /oai-ran
RUN /bin/sh oaienv && \
    cd cmake_targets/ && \
    ./build_oai -w AW2SORI -t Ethernet

#start from scratch for target executable
FROM $BASE_IMAGE AS oai-gnb-aw2s
ENV TZ=Europe/Paris

RUN dnf update -y && \
    dnf install -y \
        procps-ng \
        libXpm \
        libX11 \
        gdb \
        lksctp-tools \
        tzdata \
        net-tools \
        iputils \
        yaml-cpp-devel && \
    echo "/usr/local/lib" > /etc/ld.so.conf.d/local-lib.conf && \
    echo "/usr/local/lib64" >> /etc/ld.so.conf.d/local-lib.conf

COPY ./libori.so /usr/local/lib

WORKDIR /opt/oai-gnb-aw2s/bin
COPY --from=gnb-build /oai-ran/cmake_targets/ran_build/build/nr-softmodem ./
COPY ./docker/scripts/gnb-aw2s_entrypoint.sh /opt/oai-gnb-aw2s/bin/entrypoint.sh

COPY --from=gnb-build \
    /oai-ran/cmake_targets/ran_build/build/liboai_eth_transpro.so \
    /oai-ran/cmake_targets/ran_build/build/librfsimulator.so \
    /oai-ran/cmake_targets/ran_build/build/libaw2sori_transpro.so \
    /oai-ran/cmake_targets/ran_build/build/libcoding.so \
    /oai-ran/cmake_targets/ran_build/build/libparams_libconfig.so \
    /oai-ran/cmake_targets/ran_build/build/libdfts.so \
    /oai-ran/cmake_targets/ran_build/build/libldpc*.so \
    /oai-ran/cmake_targets/ran_build/build/libtelnetsrv.so \
    /oai-ran/cmake_targets/ran_build/build/libparams_yaml.so \
    /usr/local/lib/

COPY --from=gnb-base \
    /lib64/libconfig.so.11 \
    /lib64/libforms.so.2 \
    /lib64/

RUN ln -s /usr/local/lib/libaw2sori_transpro.so /usr/local/lib/libthirdparty_transpro.so && \
    ln -s /usr/local/lib/liboai_eth_transpro.so /usr/local/lib/liboai_transpro.so && \
    ldconfig && \
    echo "---- ldd on executable nr-softmodem ----" && \
    ldd /opt/oai-gnb-aw2s/bin/nr-softmodem && \
    echo "---- ldd on shared libraries ----" && \
    ldd /usr/local/lib/liboai_eth_transpro.so \
        /usr/local/lib/librfsimulator.so \
        /usr/local/lib/libaw2sori_transpro.so \
        /usr/local/lib/libcoding.so \
        /usr/local/lib/libparams_libconfig.so \
        /usr/local/lib/libdfts.so \
        /usr/local/lib/libldpc*.so \
        /usr/local/lib/libtelnetsrv.so

WORKDIR /opt/oai-gnb-aw2s

COPY --from=gnb-base /usr/local/bin/yq /usr/local/bin/yq
COPY --from=gnb-base /tini /tini
ENTRYPOINT ["/tini", "-v", "--", "/opt/oai-gnb-aw2s/bin/entrypoint.sh"]
CMD ["/opt/oai-gnb-aw2s/bin/nr-softmodem"]
